### ISSUE TITLE
Jar files missing

### ISSUE THREAD

**Issue by JeanMathew2** [favu100/b2program#1]
import de.prob.parser.ast.nodes.DeclarationNode;
import de.prob.parser.ast.nodes.expression.ExprNode;
import de.prob.parser.ast.nodes.expression.ExpressionOperatorNode;
import de.prob.parser.ast.nodes.expression.IdentifierExprNode;
import de.prob.parser.ast.nodes.expression.NumberNode;
import de.prob.parser.ast.nodes.predicate.PredicateNode;
import de.prob.parser.ast.nodes.predicate.PredicateOperatorNode;
import de.prob.parser.ast.nodes.predicate.PredicateOperatorWithExprArgsNode;
etc are missing. The external jar files are not available online either. 
Any leads on this will be highly appreciated.

**Comment by favu100** [comment]
Hello Jean,

these classes are included via https://github.com/hhu-stups/antlr-parser .
Did you try to build the project e.g. by ./gradlew idea?

**Comment by JeanMathew2** [comment]
No. Will do that. Thanks!! :)
